# -*- coding: utf-8 -*-
"""Real_time_facerecognition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1nUnfn2MDQXaVUH9SCqzNHZX7MDRGPc
"""

!pip install mediapipe==0.10.14

import cv2
import numpy as np
import mediapipe as mp
import dlib

# Open the camera
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Failed to open the camera.")
    exit()

# Dlib HOG face detector + shape predictor
hog_face_detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")

# Initialize MediaPipe Face Mesh
mpDraw = mp.solutions.drawing_utils
mpFaceMesh = mp.solutions.face_mesh
faceMesh = mpFaceMesh.FaceMesh(max_num_faces=2)
drawSpec = mpDraw.DrawingSpec(thickness=1, circle_radius=1)

# Scaling constants (as in your original code)
scale_factor = 0.00241  # Depends on the webcam
distance_in_pixels_eye = 78.04903229380874  # Depends on your calibration/program
distance_in_pixels_ear = 48.846744643447    # Depends on your calibration/program

def convert_pixels_to_mm_eye(dist_pix):
    return dist_pix * scale_factor

def convert_pixels_to_mm_ear(dist_pix):
    return dist_pix * scale_factor

while True:
    success, img = cap.read()
    if not success:
        print("Failed to read frame from the camera.")
        break

    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = faceMesh.process(imgRGB)

    # Convert to grayscale for dlib
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = hog_face_detector(gray, 1)

    # Draw MediaPipe Face Mesh
    if results.multi_face_landmarks:
        for faceLms in results.multi_face_landmarks:
            mpDraw.draw_landmarks(
                img,
                faceLms,
                mpFaceMesh.FACEMESH_CONTOURS,
                drawSpec,
                drawSpec
            )
            for id, lm in enumerate(faceLms.landmark):
                ih, iw, ic = img.shape
                x, y = int(lm.x * iw), int(lm.y * ih)
                cv2.putText(
                    img,
                    str(id),
                    (x, y),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.2,
                    (255, 255, 255),
                    1
                )

        # Example: use specific landmark indices for eye–ear points (MediaPipe indices!)
        # These indices are examples; adjust them to the exact points you need.
        ih, iw, ic = img.shape
        faceLms0 = results.multi_face_landmarks[0]

        # Left/right eye and ear (example MediaPipe Face Mesh indices)
        left_eye_idx = 388
        right_eye_idx = 362
        left_ear_idx = 372
        right_ear_idx = 340

        left_eye_lm = faceLms0.landmark[left_eye_idx]
        right_eye_lm = faceLms0.landmark[right_eye_idx]
        left_ear_lm = faceLms0.landmark[left_ear_idx]
        right_ear_lm = faceLms0.landmark[right_ear_idx]

        left_eye = np.array([int(left_eye_lm.x * iw), int(left_eye_lm.y * ih)])
        right_eye = np.array([int(right_eye_lm.x * iw), int(right_eye_lm.y * ih)])
        left_ear = np.array([int(left_ear_lm.x * iw), int(left_ear_lm.y * ih)])
        right_ear = np.array([int(right_ear_lm.x * iw), int(right_ear_lm.y * ih)])

        # Distances in pixels
        distance_between_eyes = np.linalg.norm(right_eye - left_eye)
        distance_between_ears = np.linalg.norm(right_ear - left_ear)

        # Convert distances to millimeters (according to your original logic)
        mm_distance_between_eyes = convert_pixels_to_mm_eye(
            int(distance_between_eyes * distance_in_pixels_eye)
        )
        mm_distance_between_ears = convert_pixels_to_mm_ear(
            int(distance_between_ears * distance_in_pixels_ear)
        )

        print(f"Distance between eyes: {mm_distance_between_eyes:.2f} mm.")
        print(f"Distance between ears: {mm_distance_between_ears:.2f} mm.")

    # Show the result frame
    cv2.imshow('img', img)

    # Exit on 'q' key
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release resources
cap.release()
cv2.destroyAllWindows()